name: Build and Publish

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Important for version calculation with GitVersion
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore CRISP.sln
    
    - name: Build
      run: dotnet build CRISP.sln --configuration Release --no-restore
    
    - name: Test
      run: dotnet test CRISP.sln --configuration Release --no-build --verbosity normal
    
    - name: Create NuGet packages
      run: |
        mkdir -p nuget-packages
        dotnet pack CRISP/CRISP.csproj -c Release -o nuget-packages
        dotnet pack CRISP.InjectionGenerator/CRISP.InjectionGenerator.csproj -c Release -o nuget-packages
    
    - name: Upload NuGet packages as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: nuget-packages/*.nupkg
        retention-days: 7

  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    
    steps:
    - name: Download NuGet packages
      uses: actions/download-artifact@v4
      with:
        name: nuget-packages
        path: nuget-packages
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Publish to NuGet
      run: |
        for package in nuget-packages/*.nupkg; do
          echo "Publishing package: $package"
          dotnet nuget push "$package" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        done
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: nuget-packages/*.nupkg
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}